# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 236175419fd145c826a1410d973034833337cc5f06bbafae1f9e5a100c947b8772319d4fd7b14b6c29bf006d60b07abef5b109fb49e09229fb5244f64584ce8c

test:
  secret_key_base: c6c7eefb97caf27c86c283a51c69ddedcc93b37c464f625e8acf32794a629826c9267d18b421310d4b6b7236ef3ba17fd3a26af64053c792641559944dacf3c7

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
